TestReport
MariaJose319/workshop-api-testing-js-QAbootcamp pull request #4
Opened 2022-06-25 22:26 UTC by MariaJose319

![image](https://user-images.githubusercontent.com/90917883/175792224-3074d6bf-6bb6-4bea-81c5-d7b2fe81e6bd.png)

2022-06-25 22:27 UTC, manuelq12 submitted a review, later dismissed
🏅

2022-06-25 22:29 UTC, manuelq12 requested changes

2022-06-25 22:29 UTC, manuelq12 commented on package.json
> +    "mochawesome": "^7.1.3"
As it is a Dev Dependency, it shouldn't be here
Mochawesome must be in the devDependencies

2022-06-25 22:30 UTC, manuelq12 commented on package.json
> +    "mochawesome": "^7.1.3"
```suggestion
    `npm uninstall mochawesome`
    `npm install mochawesome -D`
```

2022-06-28 15:24 UTC, MariaJose319 commented on package.json
> +    "mochawesome": "^7.1.3"
![image](https://user-images.githubusercontent.com/90917883/176217838-276bd7ea-53ed-4c4c-bd6e-40da6145eff8.png)
I've already changed it. Thanks.

2022-06-28 15:46 UTC, manuelq12 approved these changes
LGTM 👍

2022-06-28 17:44 UTC, merged